### ISSUE TITLE
Extension breaking Invision app and Github emoji autocomplete

### ISSUE THREAD

**Issue by khamusa** [kgopi/BackboneViewInspector#3] opened 2016-10-06 10:38 UTC
Hello,

first of all thanks for developing this extension. It's been useful for our team countless times.

I've run into a problem now. I'm trying to use **invisionapp.com**. When trying to access any board on invisionapp with the extension enabled, I get the following console errors and the UI breaks:

`Uncaught TypeError: Cannot assign to read only property 'watch' of object '#<Object>'`

with the following backtrace:
![one](https://cloud.githubusercontent.com/assets/1708578/19149243/2da60e84-8bc1-11e6-9198-7cbc732cef8b.png)

And then also the following invision-specific errors:

```
ReferenceError: InvBoards is not defined
    at https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:857:593
    at o (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:206:2780)
    at c (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:210:15873)
    at d.e [as _subscribe] (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:210:16049)
    at d.Ca.Observable.kc.subscribe.kc.forEach (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:207:470)
    at b.subscribeCore (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:208:4242)
    at b.o (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:206:2780)
    at c (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:207:1013)
    at b.d [as _subscribe] (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:207:1182)
    at b.Ca.Observable.kc.subscribe.kc.forEach (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:207:470)
    at b.subscribeCore (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:208:685)
    at b.o (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:206:2780)
    at c (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:207:1013)
    at b.d [as _subscribe] (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:207:1182)
    at b.Ca.Observable.kc.subscribe.kc.forEach (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:207:470)
    at c.onNext (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:207:17169) <ul id="main_nav" inv-big-nav-dropdown="">
ReferenceError: InvScreens is not defined
    at new Controller (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:753:3944)
    at d (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:26:14662)
    at Object.instantiate (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:26:14798)
    at https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:26:31252
    at https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:26:24253
    at r (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:26:890)
    at v (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:26:24118)
    at g (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:26:20938)
    at https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:26:20565
    at link (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:29:778)
    at v (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:26:24600)
    at g (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:26:20938)
    at https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:26:20565
    at https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:26:21410
    at x (https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:26:23244)
    at https://projects.invisionapp.com/assets/apps/d/dist/invision.min.js?v=201610052222:29:445 <div ng-class="views[subview].cssClass" ng-include=" '/assets/apps/d/views/project/' + views[subview].view " autoscroll="views[subview].autoscroll" class="ng-scope">
```

Disabling the extension eliminates the issue.

I paid particular attention to `/data/gemoji.json` on the first backtrace, since it's been a while my github emoji autocomplete doesn't work (when you type `:` and it autocompletes with emoji options). So, I disabled the extension and found out the autocomplete would work again. Unfortunately no error is output to the console when loading github with/without the extension enabled.

Any ideas on what could be causing this? I'll try running more tests to make sure this is not about the interaction of the extension with other extensions, will let you know the results.

Thanks in advance, appreciate any help!

**EDIT**: forgot to mention, the installed extension is v.0.1.2 and Backbone Debugger 0.3.1

**Comment by gs-kgopi** [comment] 2016-10-06 10:54
Thanks for using the extension @khamusa !!
Let me understand the issue.. and will come back to you, if I need any further help.

**Comment by gs-kgopi** [comment] 2016-10-06 11:33
@khamusa 

Can you please share the reproducible steps / environment (with steps to follow).. 

It will help me a lot !!

**Comment by khamusa** [comment] 2016-10-06 12:44
Hi @gs-kgopi thanks for the quick reply.

Steps to reproduce are simple. For invision you just have to open a project (you will need an account there =[) and try loading it. For github, I just reload the page, open up an issue or pull request content to edit, type `:` and the autocomplete for emojis do not appear (it should). In any case, other team members also use the extension and don't seem to be having the same problem. I just tested keeping only Backbone Inspector + View Inspector and it works ok, so it's likely an issue with another extension. 

Given that, I'd ask you to not waste your time on this yet. Once I finish my work today I'll try enabling one of my other extensions one at a time to find out which one breaks Invision / github autocomplete. Once I find out which, we can investigate if there is anything we can do here to prevent this type of incompatibility.

Thanks again

**Comment by kgopi** [comment] 2016-10-06 16:04
Hi @khamusa 

I have fixed the issue.. and published newer version 0.1.3 (check it after sometime..... since chrome showing status as **Publishing in progress**..)

Please validate the issue from your side.. and let me know the status..

**Comment by khamusa** [comment] 2016-10-07 14:31
@kgopi thanks for the quick resolution of this! The extension updated and is now working perfectly!

Great job! thanks!

**Comment by gs-kgopi** [comment] 2016-10-07 14:33
@khamusa  👍 

Closing the ticket !!

**Closed as completed by gs-kgopi** 2016-10-07 14:33 UTC
Labels: bug
